<a href="https://colab.research.google.com/github/Cann-Emma/DS1002-zgb8ts/blob/main/homework/week-6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework - Week 6

Complete the following blocks as specified in the directions. Run each cell to return the desired output. Save your notebook back to your GitHub repository and submit the GitHub URL for your notebook for review.

# Pandas

## 1. Fetch and Load Data
In class we created a DataFrame using the `read_csv` method. Go to https://catalog.data.gov/dataset/electric-vehicle-population-data and download the CSV format of the "Electric Vehicle Population Data" dataset. Then upload it to Google Colab.

Load that data into a Pandas DataFrame and display the first 20 rows. Show your work.

In [19]:
# Set up pandas and populate the dataframe above using the raw data. Then continue to work with the dataframe in the questions below.
import numpy as np
import pandas as pd
EV_pop= pd.read_csv('Electric_Vehicle_Population_Data.csv')

In [20]:
# Format a command that how many rows and columns are in this dataset.
EV_pop.shape

(150482, 17)

In [21]:
# Format a command that displays every other row of records 1000 through 1999, and the columns "City", "State", "Model Year", and "Make".
EV_pop.loc[1000:1999:9, ['City', 'State', 'Model Year', 'Make']]

          City State  Model Year    Make
1000    Auburn    WA        2022   TESLA
1009      Kent    WA        2023   TESLA
1018  Kirkland    WA        2022     BMW
1027   Seattle    WA        2014     BMW
1036   Seattle    WA        2018   TESLA
...        ...   ...         ...     ...
1963   Redmond    WA        2021   TESLA
1972  Kirkland    WA        2021   TESLA
1981     Camas    WA        2023  TOYOTA
1990   Seattle    WA        2020  TOYOTA
1999    Seatac    WA        2022   TESLA

[112 rows x 4 columns]

# 2. Cleaning/Imputing Data

In class we reviewed methods for removing duplicate rows and handling empty cell values. Download [this data set](https://github.com/nmagee/ds1002/blob/main/data/very-messy-data.csv) and upload into Google Colab.

Create another Pandas DataFrame from that data and perform the following steps.

In [22]:
# Set up pandas and populate the dataframe above using the raw data. Then continue to work with the dataframe in the questions below.
clean_dat= pd.read_csv('very-messy-data (1).csv')

In [23]:
# Write a snippet of code that will display the number of duplicate rows exist in the DF.
clean_dat.duplicated().sum()

316

In [24]:
# Next, remove all duplicate rows using Python.
clean_dat.drop_duplicates

<bound method DataFrame.drop_duplicates of        id  sepal_length  sepal_width  petal_length  petal_width    species
0       1           3.5          2.9           1.4          0.5  virginica
1       2           3.6          3.2           3.0          0.5     setosa
2       3           3.8          NaN           2.2          1.5     setosa
3       4           5.8          2.7           2.6          1.2  virginica
4       5           4.9          3.6           3.0          1.2  virginica
...   ...           ...          ...           ...          ...        ...
1311  412           NaN          3.6           2.9          0.5  virginica
1312  413           5.8          2.7           2.0          0.1  virginica
1313  414           3.3          3.7           1.3          2.8     setosa
1314  415           3.1          NaN           1.1          NaN  virginica
1315  416           4.3          2.5           1.3          1.0     setosa

[1316 rows x 6 columns]>

In [25]:
# For the FOUR columns involving sepal and petal length and width, update all NaN
# values with the column mean such that NO empty cells remain. This method
# is called "imputation" because it fills in cells in a statistically less-impactful
# way than if they were blank.

# Show how you would update those four columns in code
clean_dat.fillna(clean_dat.mean())

<ipython-input-25-ed191882c5f4>:7: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  clean_dat.fillna(clean_dat.mean())

       id  sepal_length  sepal_width  petal_length  petal_width    species
0       1      3.500000     2.900000           1.4     0.500000  virginica
1       2      3.600000     3.200000           3.0     0.500000     setosa
2       3      3.800000     2.992747           2.2     1.500000     setosa
3       4      5.800000     2.700000           2.6     1.200000  virginica
4       5      4.900000     3.600000           3.0     1.200000  virginica
...   ...           ...          ...           ...          ...        ...
1311  412      4.529662     3.600000           2.9     0.500000  virginica
1312  413      5.800000     2.700000           2.0     0.100000  virginica
1313  414      3.300000     3.700000           1.3     2.800000     setosa
1314  415      3.100000     2.992747           1.1     1.558043  virginica
1315  416      4.300000     2.500000           1.3     1.000000     setosa

[1316 rows x 6 columns]

# 3. Save to a New CSV

Preserve your updated DF to a CSV file by using the method built into Pandas.
Name the output file `very-clean-data.csv` and save it to GitHub in the same directory where you will save this homework. We will review both your Colab notebook and the cleaned data file.

In [26]:
clean_dat.to_csv('very-clean-data.csv')