<a href="https://colab.research.google.com/github/Cann-Emma/DS1002-zgb8ts/blob/main/homework/week-7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework - Week 7

Complete the following blocks as specified in the directions. Run each cell to return the desired output. Save your notebook back to your GitHub repository and submit the GitHub URL for your notebook for review.

Load the following dataset into pandas and perform the requested operations in code.

Source: https://ds1002-resources.s3.amazonaws.com/data/ride_sharing.csv

In [ ]:
# Load pandas and the data
import numpy as np
import pandas as pd
sharerd= pd.read_csv('ride_sharing.csv')
sharerd

In [2]:
# show how many rows and columns are in this dataset
sharerd.shape

(25760, 10)

In [8]:
# The first column, "duration" is seen as a string.
# Using two snippets of code, clean this column up so that
# is now an integer (int64)
sharerd.dtypes
sharerd['duration_strip']= sharerd['duration'].str.strip('minutes')
sharerd['duration_min']= sharerd['duration_strip'].astype('int')

In [9]:
# Now display the datatypes in the updated dataframe
sharerd.dtypes

duration           object
station_A_id        int64
station_A_name     object
station_B_id        int64
station_B_name     object
bike_id             int64
user_type           int64
user_birth_year     int64
user_gender        object
tire_size           int64
duration_strip     object
duration_min        int64
dtype: object

In [10]:
# Show the min and max values of ride durations (the shortest and longest rides)
# Hint: If 'df' is the name of your dataframe, simply specify the column name
# and then append the .min() or .max() methods.
print(sharerd['duration_min'].max())
print(sharerd['duration_min'].min())

1372
1

In [38]:
# Create a new dataframe object and populate it with rides that are 60 minutes or less.
# Hint: Use the .query() method for the dataframe that we used in class.
ride60= sharerd[sharerd['duration_min']<=60]

In [35]:
# Now show both the min and max values of the duration column for your new dataset.
print(ride60['duration_min'].min())
print(ride60['duration_min'].max())

1
60

In [33]:
# Using the new dataframe, update it so that is ONLY has records where
# the tire_size is 26.
tire26= ride60[ride60['tire_size']==26]
print(tire26)

         duration  station_A_id  \
0      12 minutes            81
3       4 minutes            16
6      16 minutes            67
9       5 minutes            30
12      7 minutes             3
...           ...           ...
25750  15 minutes            16
25751  15 minutes            16
25755  11 minutes            15
25756  10 minutes            15
25757  14 minutes            15

                                          station_A_name  station_B_id  \
0                                     Berry St at 4th St           323
3                                Steuart St at Market St            28
6      San Francisco Caltrain Station 2  (Townsend St...           107
9         San Francisco Caltrain (Townsend St at 4th St)            62
12          Powell St BART Station (Market St at 4th St)            27
...                                                  ...           ...
25750                            Steuart St at Market St           371
25751                            Steuart St at Market St           371
25755  San Francisco Ferry Building (Harry Bridges Pl...            34
25756  San Francisco Ferry Building (Harry Bridges Pl...            34
25757  San Francisco Ferry Building (Harry Bridges Pl...            42

                                      station_B_name  bike_id  user_type  \
0                                 Broadway at Kearny     5480          2
3                       The Embarcadero at Bryant St     1883          1
6                              17th St at Dolores St     1035          2
9                        Victoria Manalo Draves Park      333          1
12                           Beale St at Harrison St     1863          3
...                                              ...      ...        ...
25750                     Lombard St at Columbus Ave     4372          2
25751                     Lombard St at Columbus Ave     5246          1
25755                 Father Alfred E Boeddeker Park     5063          1
25756                 Father Alfred E Boeddeker Park     5411          2
25757  San Francisco City Hall (Polk St at Grove St)     5157          2

       user_birth_year user_gender  tire_size duration_strip  duration_min
0                 1959        Male         26            12             12
3                 1979        Male         26             4              4
6                 1981        Male         26            16             16
9                 1994        Male         26             5              5
12                1998        Male         26             7              7
...                ...         ...        ...            ...           ...
25750             1994        Male         26            15             15
25751             1995        Male         26            15             15
25755             2000        Male         26            11             11
25756             1998        Male         26            10             10
25757             1995        Male         26            14             14

[12761 rows x 12 columns]

In [39]:
# Finally, produce a count of all records with FEMALE riders
# using the 26-inch wheeled rental bikes for their rentals of
# one hour or less.
tire26[(tire26['user_gender']== 'Female') & (tire26['duration_min']<=1)]

,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender,tire_size,duration_strip,duration_min
45,1 minutes,67,San Francisco Caltrain Station 2 (Townsend St...,64,5th St at Brannan St,2436,2,1990,Female,26,1,1
441,1 minutes,5,Powell St BART Station (Market St at 5th St),5,Powell St BART Station (Market St at 5th St),4706,2,1985,Female,26,1,1
3262,1 minutes,3,Powell St BART Station (Market St at 4th St),21,Montgomery St BART Station (Market St at 2nd St),3474,2,1993,Female,26,1,1
4299,1 minutes,67,San Francisco Caltrain Station 2 (Townsend St...,67,San Francisco Caltrain Station 2 (Townsend St...,3309,2,1973,Female,26,1,1
4601,1 minutes,21,Montgomery St BART Station (Market St at 2nd St),20,Mechanics Monument Plaza (Market St at Bush St),2743,2,1977,Female,26,1,1
5349,1 minutes,15,San Francisco Ferry Building (Harry Bridges Pl...,15,San Francisco Ferry Building (Harry Bridges Pl...,5380,3,1990,Female,26,1,1
5351,1 minutes,15,San Francisco Ferry Building (Harry Bridges Pl...,15,San Francisco Ferry Building (Harry Bridges Pl...,4836,3,1990,Female,26,1,1
8589,1 minutes,3,Powell St BART Station (Market St at 4th St),5,Powell St BART Station (Market St at 5th St),3062,3,1988,Female,26,1,1
8799,1 minutes,3,Powell St BART Station (Market St at 4th St),3,Powell St BART Station (Market St at 4th St),2310,1,1998,Female,26,1,1
9837,1 minutes,16,Steuart St at Market St,15,San Francisco Ferry Building (Harry Bridges Pl...,45,2,1990,Female,26,1,1
9850,1 minutes,16,Steuart St at Market St,15,San Francisco Ferry Building (Harry Bridges Pl...,1884,1,1984,Female,26,1,1
13863,1 minutes,30,San Francisco Caltrain (Townsend St at 4th St),67,San Francisco Caltrain Station 2 (Townsend St...,4994,2,1988,Female,26,1,1
14309,1 minutes,30,San Francisco Caltrain (Townsend St at 4th St),30,San Francisco Caltrain (Townsend St at 4th St),4626,2,1902,Female,26,1,1
15447,1 minutes,21,Montgomery St BART Station (Market St at 2nd St),21,Montgomery St BART Station (Market St at 2nd St),5360,2,2000,Female,26,1,1
15598,1 minutes,21,Montgomery St BART Station (Market St at 2nd St),21,Montgomery St BART Station (Market St at 2nd St),2246,3,1973,Female,26,1,1
16035,1 minutes,15,San Francisco Ferry Building (Harry Bridges Pl...,15,San Francisco Ferry Building (Harry Bridges Pl...,5157,2,1986,Female,26,1,1
20865,1 minutes,21,Montgomery St BART Station (Market St at 2nd St),21,Montgomery St BART Station (Market St at 2nd St),5032,2,1996,Female,26,1,1